import os
import numpy as np
import pandas as pd
from ..models.pyddm_model import create_model

# In order to ensure reproducibility, set the seed right before all simulate calls,
# but after generate_fixations. In the future, I will discuss rng settings with professor.
def simulate(dt, model_conditions, trials, seed=42, save_results=True):
    # PyDDM has a default seed keyword that makes uniform brownian motion sampling.
    # Therefore, we need to set the seed for each trial here.

    master_rng = np.random.default_rng(seed)
    trial_seeds = master_rng.integers(0, 2**32 - 1, size=len(trials))

    model = create_model(model_conditions['drift_rate'], model_conditions['theta'], model_conditions['noise'], dt)

    results_df = list()

    for trial, trial_seed in zip(trials, trial_seeds):
        res = model.simulate_trial(conditions=trial, rk4=False, seed=trial_seed)
        original_fixation = trial['fixation'] # The original tuple generated by generate fixations
        trial_fixation = trial['fixation'][:len(res)] # The tuple including only fixations used in the trial
        trial_RT = round(len(trial_fixation)*dt, 3)
        if res[-1] >= 1:
            choice = 0
        elif res[-1] <= -1:
            choice = 1
        else:
            raise ValueError(f'Simulation ended before a decision was reached with last relative decision value of {res[-1]} but boundaries {model._bounddep.B} and {-1 * model._bounddep.B}. Please extend T_dur or modify parameters.')

        results_df.append({'trajectory': res, 'avgWTP_left': trial['avgWTP_left'], 'avgWTP_right': trial['avgWTP_right'], 'fixation': original_fixation, 'RT': trial_RT, 'choice': choice})

    results_df = pd.DataFrame(results_df)
    if save_results:
        simulated_df = results_df[['choice', 'RT', 'avgWTP_left', 'avgWTP_right', 'fixation']]
        if not os.path.exists('simulated_data'):
            os.makedirs('simulated_data')
        simulated_df.to_csv(os.path.join('simulated_data', f"sim_trials_s{seed}_d{model_conditions['drift_rate']}_t{model_conditions['theta']}_n{model_conditions['noise']}.csv"), index=False)
    return results_df